Update to Menu Scene
Error when trying to start game:
NullReferenceException: Object reference not set to an instance of an object
Menu.OnStartGameButton () (at Assets/Scripts/Menu.cs:136)